# Generated by Django 4.2.27 on 2026-01-01 14:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True,
                                           serialize=False,
                                           verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True)),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('image', models.ImageField(upload_to='')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('ingredients', models.TextField()),
                ('prep_time', models.PositiveIntegerField()),
                ('cook_time', models.PositiveIntegerField()),
                ('method', models.TextField()),
                ('servings', models.PositiveIntegerField()),
                ('difficulty', models.PositiveIntegerField(choices=[
                    (1, 'Easy'), (2, 'Medium'), (3, 'Hard')])),
                ('status', models.IntegerField(choices=[
                    (0, 'Draft'), (1, 'Published')], default=0)),
                ('author', models.ForeignKey
                 (on_delete=django.db.models.deletion.CASCADE,
                  related_name='recipes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
