# Generated by Django 4.2.27 on 2026-01-02 20:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                                           primary_key=True, serialize=False,
                                           verbose_name='ID')),
                ('content', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('edited_on', models.DateTimeField(auto_now=True)),
                ('approved', models.IntegerField(choices=[
                    (0, 'Unapproved'), (1, 'Approved')], default=0)),
                ('author', models.ForeignKey
                 (on_delete=django.db.models.deletion.CASCADE,
                  related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('comment_on', models.ForeignKey
                 (on_delete=django.db.models.deletion.CASCADE,
                  related_name='comments', to='recipes.recipe')),
            ],
        ),
    ]
